services:
  redis:
    image: redis:8.0.5-alpine
    container_name: trackstack-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 300 10 --loglevel warning

volumes:
  redis_data:
