-- ============================
-- PLAYLISTS
-- ============================

-- Drop default and attached sequence
ALTER TABLE playlists ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS playlists_id_seq;

-- Change type and add identity
ALTER TABLE playlists
    ALTER COLUMN id TYPE BIGINT,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;


-- ============================
-- TRACKS
-- ============================

ALTER TABLE tracks ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS tracks_id_seq;

ALTER TABLE tracks
    ALTER COLUMN id TYPE BIGINT,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;


-- ============================
-- TAGS
-- ============================

ALTER TABLE tags ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS tags_id_seq;

ALTER TABLE tags
    ALTER COLUMN id TYPE BIGINT,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;



